/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Automatically scans entire /docs folder
    },
  ],
};

module.exports = sidebars;
